name: model-wine-quality
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Env
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          python train.py
      - name: Metrics Report
        run: |
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          cml-send-comment report.md
          
      - name: Test with pytest
        run: |
          pytest
