#name: model-wine-quality
#on: [push]
#
#jobs:
#  train-and-report:
#    runs-on: ubuntu-latest
#    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
#    steps:
#      - uses: actions/checkout@v3
#      - name: Wine Quality
#        env:
#          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          pip install --upgrade pip
#          pip install -r requirements.txt
#          python train.py
#
#          echo "Training Finished"
#
#          echo "## Metrics" >> report.md
#          echo -e "## Plots\n### ROC Curve" >> report.md
#          echo -e "\n### Precision and Recall Curve" >> report.md
#
#          echo '![](./outputs/feature_importance.png "Confusion Matrix")' >> report.md
#          cml comment create report.md
#
#      - name: Test with pytest
#        run: |
#         pytest
#

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10.10]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          cd scripts
          chmod +x run_tests.sh
          ./run_tests.sh